<?php
/**
 * Boomstrap
 *
 * @category    design
 * @package     boomstrap
 * @copyright   Copyright (c) 2012 Holzweg e-commerce solutions (http://www.holzweg.com)
 * @license     http://www.apache.org/licenses/LICENSE-2.0  Apache License v2.0
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
        <?php foreach ($_productCollection as $_product): ?>
            <div class="row">
                <div class="span2">
                    <?php // Product Image ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" rel="popover" data-placement="left"><img class="thumbnail" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                </div>
                <?php // Product description ?>
                <article class="span4">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <p>
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <br />
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </p>
                    <p><?php echo $this->getPriceHtml($_product, true) ?></p>
                    <div class="btn-group well">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-small btn-success" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="icon-shopping-cart icon-white"></i> <?php echo $this->__('Add to Cart') ?></button>
                        <?php else: ?>
                            <p class="label out-of-stock"><?php echo $this->__('Out of stock') ?></p>
                        <?php endif; ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn btn-small"><i class="icon-gift"></i> <?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a href="<?php echo $_compareUrl ?>" class="btn btn-small"><i class="icon-leaf"></i> <?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                    </div>
                </article>
            </div>
        <?php endforeach; ?>
        <!-- @varien <script type="text/javascript">decorateList('products-list', 'none-recursive')</script> -->

    <?php else: ?>

    <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php if ($i++%$_columnCount==0): ?>
            <div class="row">
            <?php endif ?>
                <article class="span<?php echo 6 / $_columnCount ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" rel="popover" data-placement="top"><img class="thumbnail well" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <h2><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php /* Up to a certain width of text only @todo responsiveness @warning breaks in php < 5.3 */ $name = $_helper->productAttribute($_product, $_product->getName(), 'name'); echo strstr( wordwrap( $name, 10, '%STOP%', true ), '%STOP%', true ) ?: $name ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <div class="well">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <div class="btn-group well">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-small btn-success" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="icon-shopping-cart icon-white"></i> <?php echo $this->__('Add to Cart') ?></button>
                        <?php else: ?>
                            <p><span class="label-warning"><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn btn-small"><i class="icon-gift"></i> <?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a href="<?php echo $_compareUrl ?>" class="btn btn-small"><i class="icon-leaf"></i> <?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                    </div>
                </article>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </div>
            <?php endif ?>
            <?php endforeach ?>
            <!-- @varien <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script> -->
    <?php endif; ?>

    <?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>
