<?php
/**
 * Boomstrap
 *
 * @category    design
 * @package     boomstrap
 * @copyright   Copyright (c) 2012 Holzweg e-commerce solutions (http://www.holzweg.com)
 * @license     http://www.apache.org/licenses/LICENSE-2.0  Apache License v2.0
 */
?>

<?php
/**
 * @see Mage_Paypal_Block_Logo
 */
?>
<aside class="well">
    <a href="#" title="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" onclick="javascript:window.open('<?php echo $this->getAboutPaypalPageUrl() ?>','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?php echo $this->escapeHtml($this->getLogoImageUrl()) ?>" alt="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" title="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" /></a>
</aside>
