<?php
/**
 * Boomstrap
 *
 * @category    design
 * @package     boomstrap
 * @copyright   Copyright (c) 2012 Holzweg e-commerce solutions (http://www.holzweg.com)
 * @license     http://www.apache.org/licenses/LICENSE-2.0  Apache License v2.0
 */
?>

<h1><?php echo $this->__('Redirecting...') ?></h1>
<?php if($this->getMessage()): ?>
    <p><?php echo $this->getMessage() ?></p>
<?php endif; ?>
<?php echo $this->getRedirectOutput() ?>
<?php if(!$this->isHtmlFormRedirect()): ?>
    <p><?php echo $this->__('Click <a href="%s">here</a> if nothing has happened', $this->getTargetURL()) ?></p>
<?php endif; ?>
