<?php
/**
 * Boomstrap
 *
 * @category    design
 * @package     boomstrap
 * @copyright   Copyright (c) 2012 Holzweg e-commerce solutions (http://www.holzweg.com)
 * @license     http://www.apache.org/licenses/LICENSE-2.0  Apache License v2.0
 */
?>
<?
    /* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="well">
    <strong><i class="icon-leaf"></i> <?php echo $this->__('Recently Viewed Products') ?></strong>
    <ol id="recently-viewed-items">
    <?php foreach ($_products as $_item): ?>
        <li>
            <a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a>
        </li>
    <?php endforeach; ?>
    </ol>
    <!-- @varien <script type="text/javascript">decorateList('recently-viewed-items');</script> -->
</div>
<?php endif; ?>
