<?php
/**
 * Boomstrap
 *
 * @category    design
 * @package     boomstrap
 * @copyright   Copyright (c) 2012 Holzweg e-commerce solutions (http://www.holzweg.com)
 * @license     http://www.apache.org/licenses/LICENSE-2.0  Apache License v2.0
 */
?>

<?php $_menu = $this->renderCategoriesMenuHtml(0, 'level-top') ?>
<?php if ($_menu): ?>
    <nav id="secondary-nav">
        <ul>
            <?php echo $_menu ?>
        </ul>
    </nav>
    <?php
 endif ?>
