<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<nav class="navbar" id="primary-nav">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="<?php echo $this->getUrl('') ?>"><?php echo Mage::app()->getStore()->getName(); ?></a>
            <nav class="nav-collapse">
                <ul class="nav">
                    <?php echo $_menu ?>
                </ul>
                <?php echo $this->getChildHtml('topSearch') ?>
            </nav>
        </div>
    </div>
</nav>
<?php endif ?>
