<?php
/**
 * Boomstrap
 *
 * @category    design
 * @package     boomstrap
 * @copyright   Copyright (c) 2012 Holzweg e-commerce solutions (http://www.holzweg.com)
 * @license     http://www.apache.org/licenses/LICENSE-2.0  Apache License v2.0
 */
?>
<div class="well">
    <?php if (strtolower(substr($this->getLinkUrl(), 0, 4)) === 'http'): ?>
        <a href="<?php echo $this->getLinkUrl() ?>" title="<?php echo $this->__($this->getImgAlt()) ?>">
    <?php elseif ($this->getLinkUrl()): ?>
        <a href="<?php echo $this->getUrl($this->getLinkUrl()) ?>" title="<?php echo $this->__($this->getImgAlt()) ?>">
    <?php endif; ?>
        <img class="thumbnail" src="<?php echo $this->getSkinUrl($this->getImgSrc()) ?>"<?php if (!$this->getLinkUrl()): ?> title="<?php echo $this->__($this->getImgAlt()) ?>"<?php endif; ?> alt="<?php echo $this->__($this->getImgAlt()) ?>" />
    <?php if ($this->getLinkUrl()): ?>
        </a>
    <?php endif ?>
</div>
